package com.ljw.web.entity;

import java.io.Serializable;
import java.util.Date;

public class Picture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.IMAGE_PATH
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.IMAGE_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private String imageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.UPLOAD_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table picture
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.ID
     *
     * @return the value of picture.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.ID
     *
     * @param id the value for picture.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.IMAGE_PATH
     *
     * @return the value of picture.IMAGE_PATH
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.IMAGE_PATH
     *
     * @param imagePath the value for picture.IMAGE_PATH
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.USER_ID
     *
     * @return the value of picture.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.USER_ID
     *
     * @param userId the value for picture.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.IMAGE_NAME
     *
     * @return the value of picture.IMAGE_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.IMAGE_NAME
     *
     * @param imageName the value for picture.IMAGE_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.UPLOAD_TIME
     *
     * @return the value of picture.UPLOAD_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.UPLOAD_TIME
     *
     * @param uploadTime the value for picture.UPLOAD_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}