package com.ljw.web.entity;

import java.io.Serializable;
import java.util.Date;

public class WxAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private String wxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_CODE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private String wxCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_TYPE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Integer wxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_INTRODUCTION
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private String wxIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_IS_IDENTIFY
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Integer wxIsIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.WX_APPLET_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Long wxAppletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_account.CREATE_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_account
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.ID
     *
     * @return the value of wx_account.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.ID
     *
     * @param id the value for wx_account.ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_NAME
     *
     * @return the value of wx_account.WX_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_NAME
     *
     * @param wxName the value for wx_account.WX_NAME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_CODE
     *
     * @return the value of wx_account.WX_CODE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public String getWxCode() {
        return wxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_CODE
     *
     * @param wxCode the value for wx_account.WX_CODE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxCode(String wxCode) {
        this.wxCode = wxCode == null ? null : wxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_TYPE
     *
     * @return the value of wx_account.WX_TYPE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Integer getWxType() {
        return wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_TYPE
     *
     * @param wxType the value for wx_account.WX_TYPE
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxType(Integer wxType) {
        this.wxType = wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_INTRODUCTION
     *
     * @return the value of wx_account.WX_INTRODUCTION
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public String getWxIntroduction() {
        return wxIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_INTRODUCTION
     *
     * @param wxIntroduction the value for wx_account.WX_INTRODUCTION
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxIntroduction(String wxIntroduction) {
        this.wxIntroduction = wxIntroduction == null ? null : wxIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_IS_IDENTIFY
     *
     * @return the value of wx_account.WX_IS_IDENTIFY
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Integer getWxIsIdentify() {
        return wxIsIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_IS_IDENTIFY
     *
     * @param wxIsIdentify the value for wx_account.WX_IS_IDENTIFY
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxIsIdentify(Integer wxIsIdentify) {
        this.wxIsIdentify = wxIsIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.WX_APPLET_ID
     *
     * @return the value of wx_account.WX_APPLET_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Long getWxAppletId() {
        return wxAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.WX_APPLET_ID
     *
     * @param wxAppletId the value for wx_account.WX_APPLET_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setWxAppletId(Long wxAppletId) {
        this.wxAppletId = wxAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.USER_ID
     *
     * @return the value of wx_account.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.USER_ID
     *
     * @param userId the value for wx_account.USER_ID
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_account.CREATE_TIME
     *
     * @return the value of wx_account.CREATE_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_account.CREATE_TIME
     *
     * @param createTime the value for wx_account.CREATE_TIME
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}