package com.ljw.web.dao;

import com.ljw.web.entity.WxRgisterInfo;

public interface WxRgisterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    int insert(WxRgisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    int insertSelective(WxRgisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    WxRgisterInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    int updateByPrimaryKeySelective(WxRgisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_rgister_info
     *
     * @mbg.generated Wed May 03 21:59:17 CST 2017
     */
    int updateByPrimaryKey(WxRgisterInfo record);
}